key_bindings = [
  # General actions
  { key = "q",       command = "quit" },
  { key = "?",       command = "toggle_help" },
  { key = " ",       command = "toggle_vault_selector" },
  { key = "t",       command = "toggle_mode" },

  # Navigation
  { key = "up",      command = "scroll_up" },
  { key = "down",    command = "scroll_down" },
  { key = "ctrl+u",  command = "page_up" },
  { key = "ctrl+d",  command = "page_down" },
  { key = "k",       command = "previous" },
  { key = "j",       command = "next" },

  # Selection
  { key = "enter",   command = "select" }
]
