#!/usr/bin/env sh

set -e

make fmt-check
cargo check --locked --profile ci --workspace --all-targets
cargo clippy --profile ci --workspace --all-targets -- -D warnings
cargo test --profile ci --workspace --all-targets
cargo build --profile ci --workspace --all-targets
cargo package --no-verify --allow-dirty
