Set Theme {
  "name": "Causeway Light",
  "background": "#f2eee3",
  "foreground": "#33302a",
  "cursor": "#517a4e",
  "selection": "#e0dbc9",
  "black": "#e8e3d5",
  "red": "#a15a4d",
  "green": "#517a4e",
  "yellow": "#a67c33",
  "blue": "#46727e",
  "magenta": "#7c6484",
  "cyan": "#46727e",
  "white": "#b6ad98",
  "brightBlack": "#86806e",
  "brightRed": "#b56a5c",
  "brightGreen": "#5f8a5b",
  "brightYellow": "#b58c40",
  "brightBlue": "#557f8c",
  "brightMagenta": "#8d7597",
  "brightCyan": "#5a8b97",
  "brightWhite": "#33302a"
}

Env BASALT_THEME "causeway-light"
